[General]
ColorScheme=Sweet
FloatingFooterTrigger=BottomMouseMovement
FooterStyle=floating
GuiStyle=kvantum-dark
LastPlayedFile=file:///home/cade/Downloads/AnimePahe_Tensei_shitara_Slime_Datta_Ken_-_79_1080p_SubsPlease.mp4
RememberWindowGeometry=true
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true

[Playback]
HWDecoding=nvdec

[Playlist]
PlaybackBehavior=StopAfterLast
PlaylistWidth=191.17647058823528
Position=left
