[Audio]
Volume=100

[General]
ColorScheme=Sweet
FloatingFooterTrigger=BottomMouseMovement
FooterStyle=floating
GuiStyle=kvantum-dark
LastPlayedFile=file:///home/cade/Anime/%5BJudas%5D FateStrange Fake (Season 01) %5B1080p%5D%5BHEVC x265 10bit%5D%5BDual-Audio%5D%5BMulti-Subs/%5BJudas%5D Fate-Strange - S01E05v2.mkv
RememberWindowGeometry=true
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true

[Playback]
HWDecoding=vaapi

[Playlist]
PlaybackBehavior=StopAfterLast
PlaylistWidth=191.17647058823528
Position=left
