[General]
FullscreenOnStartUp=true
GuiStyle=Breeze
LastPlayedFile=file:///home/cade/Anime/Chainsaw.Man.The.Movie.Reze.Arc.2025.2160p.iT.WEB-DL.JAP.ENG.LAT-SPA.DDP5.1.DV.HDR.H.265-AF.mkv
ShowPreviewThumbnail=true

[Playlist]
PlaybackBehavior=StopAfterLast
PlaylistWidth=191.17647058823528
Position=left
