- name: Pre-install cargo packages step
  when: cargo_packages is defined
  block:
    - name: Check if Cargo is installed
      shell: which cargo
      register: cargo_check
      args:
        executable: /bin/bash
      failed_when: cargo_check.rc not in [0, 1]

    - name: Check if Rust is installed
      shell: which rustc
      register: rust_check
      args:
        executable: /bin/bash
      failed_when: cargo_check.rc not in [0, 1]

    - name: Download Rust Installer
      when: rust_check.rc != 0 and cargo_check.rc != 0
      get_url:
        url: https://sh.rustup.rs
        dest: "{{ ansible_env.HOME }}/Downloads/sh.rustup.rs"
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    - name: Install Rust & Cargo
      when: rust_check.rc != 0 and cargo_check.rc != 0
      shell: "{{ ansible_env.HOME }}/Downloads/sh.rustup.rs -y"
      tags:
        - rust

    - name: Ensure Cargo is in the PATH for the user
      when: rust_check.rc != 0 and cargo_check.rc != 0
      lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: 'export PATH="$HOME/.cargo/bin:$PATH"'
        state: present

- name: Install cargo packages
  become: yes
  command: cargo install "{{ item.name | default(item) }}"
  loop: "{{ cargo_packages }}"
  register: install_result
  when: cargo_packages is defined
