add_custom_hostname: false
custom_hostname: put-name-here

create_directories: true
directories:
  # I like to put my git repos in dev
  # and order them by code types
  - $HOME/dev/
  - $HOME/dev/js/
  - $HOME/dev/py/
  - $HOME/dev/csharp/
  - $HOME/dev/rust/
  - $HOME/dev/java/
  - $HOME/dev/bash/
  - $HOME/dev/local-setup/
  - $HOME/dev/automation-scripts/
  - $HOME/dev/tmp/

add_apt_repositories: true
apt_repositories:
  - repository: "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
    gpg_key: "https://packages.microsoft.com/keys/microsoft.asc"
    keyring: "/usr/share/keyrings/packages.microsoft.gpg"
  - repository: deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
    gpg_key: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
    keyring: "/usr/share/keyrings/githubcli-archive-keyring.gpg"

install_apt_packages: true
apt_packages:
  # install these if you are planning
  # on using nushell, otherwise comment them out
  # start of nushell deps
  - pkg-config
  - libssl-dev
  - build-essential
  # end of nushell deps
  - code
  - gh

install_cargo_packages: true
cargo_packages:
  - eza
  - fnm
  - ruplacer
  - hurl

install_flatpak_packages: true
flatpak_packages:
  - md.obsidian.Obsidian

install_fonts: true
installed_nerdfonts:
  - Meslo
