- name: Setup Environment
  hosts: localhost
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"

  vars_files:
    - config.yml

  tasks:
    - name: Ensure all applications are installed
      debug:
        msg: "All specified applications have been processed"
      tags: ['always']

  tasks:
      - name: Include apt packages task configuration
        when: install_apt_packages
        ansible.builtin.import_tasks:
          file: tasks/apt.yml
        tags: ["apt"]

      - name: Include cargo packages task configuration
        when: install_cargo_packages
        ansible.builtin.import_tasks:
          file: tasks/cargo.yml
        tags: ["cargo"]

      - name: Include flatpak packages task configuration
        when: install_flatpak_packages
        ansible.builtin.import_tasks:
          file: tasks/flatpak.yml
        tags: ["flatpak"]

      - name: Include fonts task configuration
        when: install_fonts
        ansible.builtin.import_tasks:
          file: tasks/fonts.yml
        tags: ["fonts"]

      - name: Include hostname configuration
        when: add_custom_hostname
        ansible.builtin.import_tasks:
          file: tasks/hostname.yml
        tags: ["hostname"]

      - name: Include create directories configuration
        when: create_directories
        ansible.builtin.import_tasks:
          file: tasks/create-directories.yml
        tags: ["create-directories"]
